// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Person
*/
package protodemo

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type Sex int32

const (
	Sex_MAN     Sex = 0
	Sex_WOMAN   Sex = 1
	Sex_SCREATE Sex = 2
)

var Sex_name = map[int32]string{
	0: "MAN",
	1: "WOMAN",
	2: "SCREATE",
}
var Sex_value = map[string]int32{
	"MAN":     0,
	"WOMAN":   1,
	"SCREATE": 2,
}

func (x Sex) String() string {
	return proto1.EnumName(Sex_name, int32(x))
}
func (Sex) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Person struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Sex   Sex    `protobuf:"varint,2,opt,name=sex,enum=proto.Sex" json:"sex,omitempty"`
	IdNum string `protobuf:"bytes,3,opt,name=idNum" json:"idNum,omitempty"`
	Bio   string `protobuf:"bytes,4,opt,name=bio" json:"bio,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetSex() Sex {
	if m != nil {
		return m.Sex
	}
	return Sex_MAN
}

func (m *Person) GetIdNum() string {
	if m != nil {
		return m.IdNum
	}
	return ""
}

func (m *Person) GetBio() string {
	if m != nil {
		return m.Bio
	}
	return ""
}

func init() {
	proto1.RegisterType((*Person)(nil), "proto.Person")
	proto1.RegisterEnum("proto.Sex", Sex_name, Sex_value)
}

func init() { proto1.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 164 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x49, 0x5c,
	0x6c, 0x01, 0xa9, 0x45, 0xc5, 0xf9, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x0c, 0x17, 0x73, 0x71, 0x6a, 0x85, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x9f, 0x11, 0x17, 0x44, 0xa7, 0x5e, 0x70, 0x6a, 0x45, 0x10, 0x48, 0x58,
	0x48, 0x84, 0x8b, 0x35, 0x33, 0xc5, 0xaf, 0x34, 0x57, 0x82, 0x19, 0xac, 0x05, 0xc2, 0x11, 0x12,
	0xe0, 0x62, 0x4e, 0xca, 0xcc, 0x97, 0x60, 0x01, 0x8b, 0x81, 0x98, 0x5a, 0x6a, 0x5c, 0xcc, 0xc1,
	0xa9, 0x15, 0x42, 0xec, 0x5c, 0xcc, 0xbe, 0x8e, 0x7e, 0x02, 0x0c, 0x42, 0x9c, 0x5c, 0xac, 0xe1,
	0xfe, 0x20, 0x26, 0xa3, 0x10, 0x37, 0x17, 0x7b, 0xb0, 0x73, 0x90, 0xab, 0x63, 0x88, 0xab, 0x00,
	0x53, 0x12, 0x1b, 0xd8, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xbf, 0xa9, 0x9f,
	0xaa, 0x00, 0x00, 0x00,
}
