// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpcmsg.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	rpcmsg.proto

It has these top-level messages:
	HelloRequest
	HelloResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloResponse) Reset()                    { *m = HelloResponse{} }
func (m *HelloResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()               {}
func (*HelloResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "grpc.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "grpc.HelloResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for Controller service

type ControllerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloResponse, error)
}

type controllerClient struct {
	cc *grpc1.ClientConn
}

func NewControllerClient(cc *grpc1.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc1.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := grpc1.Invoke(ctx, "/grpc.Controller/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Controller service

type ControllerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterControllerServer(s *grpc1.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).SayHello(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.Controller/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Controller_SayHello_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "rpcmsg.proto",
}

func init() { proto.RegisterFile("rpcmsg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2a, 0x48, 0xce,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2f, 0x2a, 0x48, 0x56, 0x52,
	0xe2, 0xe2, 0xf1, 0x48, 0xcd, 0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95,
	0x34, 0xb9, 0x78, 0xa1, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0x73,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x61, 0xea, 0x60, 0x5c, 0x23, 0x67, 0x2e, 0x2e, 0xe7, 0xfc, 0xbc,
	0x92, 0xa2, 0xfc, 0x9c, 0x9c, 0xd4, 0x22, 0x21, 0x53, 0x2e, 0x8e, 0xe0, 0xc4, 0x4a, 0xb0, 0x5e,
	0x21, 0x21, 0x3d, 0x90, 0x7d, 0x7a, 0xc8, 0x96, 0x49, 0x09, 0xa3, 0x88, 0x41, 0x0c, 0x57, 0x62,
	0x48, 0x62, 0x03, 0x3b, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x5c, 0x4c, 0x00, 0x5e, 0xb0,
	0x00, 0x00, 0x00,
}
